import {StyleSheet, Dimensions} from "react-native";

const {height, width} = Dimensions.get("window");
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  btnScanSecond: {
    backgroundColor: "#ff9e1f",
    width: "70%",
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    paddingHorizontal: 10,
    margin: 10,
  },
  dataContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  btnScanOther: {
    backgroundColor: "#ff9e1f",
    width: width * 0.7,
    height: height * 0.05,
    top: "3%",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  btnScanText: {
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
    padding: 10,
  },
  titlefirsStep: {
    color: "#fff",
    fontSize: 25,
    fontWeight: "bold",
    bottom: height * 0.1,
  },
  cameraNotActiveContainer: {
    height: "30%",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  matchTitle: {
    color: "#ff9e1f",
    fontSize: 25,
    textAlign: "center",
    fontWeight: "bold",
  },
  matchingContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    height: "30%",
    marginVertical: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  productsMatch: {
    backgroundColor: "#fff",
    display: "flex",
    flexDirection: "column",
    width: "45%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    margin: 10,
    padding: 15,
  },
  productMatchTitle: {
    color: "#ff9e1f",
    fontSize: 15,
    textAlign: "center",
    fontWeight: "bold",
    textAlign: "center",
    width: width * 1,
  },
  productMatchImage: {
    width: "70%",
    height: "65%",
  },
  noInformations: {
    fontSize: 20,
    textAlign: "center",
    margin: 30,
  },

  containerOptions: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  optionButton: {
    margin: 10,
    padding: 10,
    backgroundColor: "#436B92",
    borderRadius: 5,
  },
  optionText: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  containerInventory: {
    justifyContent: "center",
    alignItems: "center",
  },
  productMatchImageInventory: {
    width: 200,
    height: 180,
    resizeMode: "contain",
    borderRadius: 20,
    marginTop: 20,
  },
  productInformatios: {
    color: "#436B92",
    fontSize: 20,
    marginBottom: "5%",
    fontWeight: "bold",
    padding: 10,
    marginVertical: 5,
  },
  inputBarCode: {
    width: "80%",
    height: "20%",
    backgroundColor: "#fff",
    borderWidth: 5,
    borderRadius: 20,
    borderColor: "#fff",
    padding: 10,
  },
  activateCameraButton: {
    width: "80%",
    height: "5%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ff9e1f",
    borderRadius: 5,
  },
  cameraView: {
    height: "40%",
    width: "70%",
    margin: 10,
  },
  activateCameraText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 15,
  },
  scannerView: {
    backgroundColor: "#436B92",
    height: "110%",
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  updateInfoButton: {
    backgroundColor: "#436B92",
    width: "70%",
    height: 50,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#436B92",
  },

  returnButton: {
    alignItems: "center",
    justifyContent: "center",
    width: "40%",
    height: "5%",
    minHeight: 40,
    backgroundColor: "#ff9e1f",
    top: "6%",
    borderRadius: 20,
    borderColor: "#ff9e1f",
    borderWidth: 1,
  },
  returnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "bold",
  },
  resetButton: {
    alignItems: "center",
    justifyContent: "center",
    width: "40%",
    height: "50%",
    minHeight: 40,
    backgroundColor: "#ff9e1f",
    borderRadius: 20,
    borderColor: "#ff9e1f",
    borderWidth: 1,
  },
  chooseOptionText: {
    textAlign: "center",
    fontSize: 20,
    marginBottom: 20,
    color: "#436B92",
    fontWeight: "bold",
  },
  upcText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
  },
  validateButton: {
    backgroundColor: "#4BB213",
    width: "60%",
    minHeight: 40,
    height: "5%",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    marginTop: 10,
  },
  validateText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 20,
  },
  employeeListContainer: {
    height: "85%",
    width: "70%",
    backgroundColor: "#436B92",
    borderRadius: 20,
  },
  employee: {
    padding: 20,
    borderBottomColor: "#fff",
    borderBottomWidth: 1,
  },
  employeeName: {
    color: "#fff",
    textAlign: "center",
    fontWeight: "500",
    fontSize: 15,
  },
  productInfoUpdateEanMenu: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "90%",
    height: "30%",
    minHeight: height * 0.3,
    borderRadius: 10,
  },
  bottomButtonsContainer: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    height: "10%",
    alignItems: "center",
    justifyContent: "space-around",
    margin: 10,
  },
  itemProduct: {
    marginBottom: 20,
    display: "flex",
    flexDirection: "row",
    width: width * 0.9,
    height: height * 0.15,
    backgroundColor: "#fff",
    borderRadius: 20,
  },
  productInfo: {
    fontWeight: "bold",
    fontSize: 15,
    margin: 5,
    textAlign: "justify",
    width: "70%",
  },
  listProductContainer: {
    width: "100%",
    height: "15%",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  headerTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
  },
  imageProductList: {
    width: "30%",
    height: "90%",
    margin: 6,
  },
  loadingMore: {
    textAlign: "center",
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
  },
  modalContainer: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
    padding: 16,
    width: "100%",
    height: "95%",
  },

  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 8,
  },
  modalImage: {
    width: 200,
    height: 200,
    marginBottom: 8,
  },
  modalCloseButton: {
    padding: 10,
    backgroundColor: "#ff9e1f",
    borderRadius: 5,
  },
  modalCloseButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  notScannableButton: {
    width: "40%",
    height: "35%",
    minHeight: 35,
    backgroundColor: "red",
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  notScannableText: {
    color: "#fff",
    fontWeight: "bold",
  },
  restockingMenuContainer: {
    height: "100%",
    width: "100%",
    backgroundColor: "#436B92",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  flatlistContainer: {
    height: "70%",
    width: "80%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  eachOrderRestocking: {
    backgroundColor: "#ff9e1f",
    width: "100%",
    marginVertical: 10,
    height: height * 0.12,
    display: "flex",
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#fff",
    borderRadius: 10,
    marginVertical: 40,
  },
  eachOrderRestocking2: {
    backgroundColor: "#ff9e1f",
    width: "100%",
    marginVertical: 10,
    height: height * 0.08,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#fff",
  },
  titleOrderRestock2: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "bold",
    textAlign: "center",
  },
  titleOrderRestock: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "bold",
    textAlign: "center",
    padding: 10,
    width: "100%",
    height: "40%",
  },
  titleHeader: {
    color: "#fff",
    fontSize: 25,
    fontWeight: "bold",
    padding: 10,
    textAlign: "center",
  },
  nbrOrder: {
    color: "#ff9e1f",
    fontSize: 18,
    marginHorizontal: 10,
    fontWeight: "bold",
    paddingVertical: 15,
    textAlign: "center",
  },
  header: {
    display: "flex",
    flexDirection: "row",
  },
  goBackButton: {
    width: "40%",
    height: "5%",
    backgroundColor: "#ff9e1f",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
  },
  goBackText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "bold",
  },
  titleOrder: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
  },
  productContainer: {
    marginVertical: 10,
    height: height * 0.14,
    width: "100%",
    flexDirection: "row",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#fff",
  },
  productImage: {
    width: "30%",
    height: "100%",
    borderRadius: 7,
  },
  productInformations: {
    width: "100%",
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
  },

  productInformationsContainer: {
    flexDirection: "column",
    width: "70%",
    padding: 10,
  },
  modalContainerProduct: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContentProduct: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 10,
    alignItems: "center",
    width: "80%",
  },
  imageProductSelected: {
    width: "40%",
    height: "25%",
    marginBottom: 10,
    borderColor: "black",
  },
  productInformationsModal: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#436B92",
    marginBottom: 10,
    textAlign: "center",
    paddingVertical: 5,
  },
  closeButton: {
    backgroundColor: "red",
    width: "40%",
    height: "5%",
    alignItems: "center",
    justifyContent: "center",
    borderEndStartRadius: 10,
    borderEndEndRadius: 10,
  },
  closeButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 17,
  },
  buttonQté: {
    width: "40%",
    height: "60%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
  },
  setQtyInput: {
    backgroundColor: "#436B92",
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#436B92",
    width: "80%",
    height: "40%",
    color: "#fff",
    textAlign: "center",
  },
  searchInput: {
    backgroundColor: "#436B92",
    width: "60%",
    height: height * 0.06,
    borderRadius: 20,
    borderColor: "#fff",
    borderWidth: 1,
    color: "#fff",
    padding: 10,
  },
  headerDirection: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
  },
  Xbutton: {
    color: "#fff",
    fontSize: 17,
    padding: 5,
  },
  EANbutton: {
    color: "#fff",
    fontSize: 20,
    borderRadius: 10,
    margin: 5,
    padding: 10,
  },
  filterPart: {
    flexDirection: "row",
    width: "100%",
    height: "10%",
    justifyContent: "space-around",
    alignItems: "center",
  },
  productScannedInfoContainer: {
    height: "80%",
    width: "101%",
    backgroundColor: "#fff",
    borderEndEndRadius: 20,
    borderEndStartRadius: 20,
    borderColor: "#436B92",
    borderWidth: 1,
  },
  productScannedImage: {
    width: "20%",
    height: "100%",
    borderRadius: 20,
    marginHorizontal: 10,
  },
  productScannedName: {
    color: "#436B92",
    fontSize: 15,
    fontWeight: "bold",
    width: "70%",
  },
  productContainerSelected: {
    borderColor: "red",
    borderWidth: 9,
    height: 150,
  },
  noProductFoundText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 25,
  },
  dluoText: {
    color: "#fff",
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
    borderColor: "green",
    backgroundColor: "green",
  },
  calendarView: {
    backgroundColor: "#436B92",
    borderRadius: 5,
    height: "60%",
    width: "100%",
  },

  bottomButtonModalCalendar: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    height: "20%",
    justifyContent: "space-around",
    marginVertical: 20,
  },
  closeCalendarButton: {
    width: "40%",
    height: "60%",
    backgroundColor: "red",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  saveDluoCalendarButton: {
    width: "40%",
    height: "60%",
    backgroundColor: "green",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  calendarTextStyle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "500",
    padding: 3,
  },
  stockUpdateContainer: {
    width: "100%",
    height: "20%",
    alignItems: "center",
    justifyContent: "center",
  },
  stockButton: {
    width: "70%",
    height: "30%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "green",
    margin: 10,
    borderRadius: 5,
  },
  updateStockText: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#fff",
  },
  loginForm: {
    backgroundColor: "#436B92",
    width: width * 0.8,
    height: height * 0.4,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  loginTitle: {
    color: "#fff",
    fontSize: 25,
    fontWeight: "bold",
  },
  loginInput: {
    width: "80%",
    height: "20%",
    backgroundColor: "#fff",
    margin: 10,
    borderRadius: 10,
    padding: 10,
  },
  errorText: {
    color: "#ff9e1f",
    fontWeight: "bold",
    fontSize: 15,
  },
  loginButton: {
    width: "60%",
    height: "10%",
    backgroundColor: "#fff",
    margin: 15,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  loginButtonText: {
    color: "#436B92",
    fontSize: 20,
    fontWeight: "bold",
  },
  resetEmployeeButton: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ff9e1f",
    margin: 10,
    borderRadius: 10,
    height: "10%",
  },
  resetEmployeeText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "bold",
  },
  logoutButton: {
    height: "15%",
    width: "100%",
    backgroundColor: "#ff9e1f",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
    top: "10%",
  },
  logoutText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "bold",
  },
  ean: {
    fontSize: 16,
    color: "#fff",
    textAlign: "center",
    fontWeight: "bold",
    marginBottom: 10,
  },
  abortEanButton: {
    height: "50%",
    top: 0,
    backgroundColor: "red",
    borderColor: "red",
  },
});
